const CONST_ININVOICEVIEW = 'ROLE_FIN_FATURAMENTO_NF_FATURA_VISUALIZAR';
const CONST_ININVOICEEMIT = 'ROLE_FIN_FATURAMENTO_NF_FATURA_EMITIR';
const CONST_ININVOICECANCEL = 'ROLE_FIN_FATURAMENTO_NF_FATURA_CANCELAR';
const CONST_ININVOICEDOWNLOAD = 'ROLE_FIN_FATURAMENTO_NF_FATURA_DOWNLOAD';
const CONST_ININVOICESEND = 'ROLE_FIN_FATURAMENTO_NF_FATURA_ENVIAR';
const CONST_INIMPORTFILEINCLUDE = 'ROLE_FIN_FATURAMENTO_NF_IMPORTAR_ARQ_INCLUIR';
const CONST_INDUPLICATEBILLETEMIT = 'ROLE_FIN_FATURAMENTO_NF_FATURA_SEGUNDA_VIA_BOLETO_EMITIR';
const CONST_INISSUANCECALENDARVIEW = 'ROLE_FIN_FATURAMENTO_CALENDARIO_EMISSAO_VISUALIZAR';
const CONST_INBILLINGHISTORYVIEW = 'ROLE_FIN_FATURAMENTO_HISTORICO_VISUALIZAR';
const CONST_ININVOICINGREPORTVIEW = 'ROLE_FIN_FATURAMENTO_RELATORIO_VISUALIZAR';
const CONST_DUNNINGVIEW = 'ROLE_FIN_FATURAMENTO_COB_REG_COBRANCA_VISUALIZAR';
const CONST_DUNNINGINCLUDE = 'ROLE_FIN_FATURAMENTO_COB_REG_COBRANCA_INCLUIR';
const CONST_DUNNINGEDIT = 'ROLE_FIN_FATURAMENTO_COB_REG_COBRANCA_EDITAR';
const CONST_OVERDUEPANELVIEW = 'ROLE_FIN_FATURAMENTO_COB_INADIMPLENCIA_VISUALIZAR';
const CONST_OVERDUEPANELINCLUDE = 'ROLE_FIN_FATURAMENTO_COB_INADIMPLENCIA_INCLUIR';
const CONST_RECEIPTS = 'ROLE_FIN_FATURAMENTO_RECEBIMENTOS_VISUALIZAR';
const CONST_INCLIENTBALANCEVIEW = 'ROLE_FIN_FATURAMENTO_PAG_CONTROLE_SALDO_VISUALIZAR'
const CONST_INCLIENTBALANCEEMIT = 'ROLE_FIN_FATURAMENTO_PAG_CONTROLE_SALDO_BOLETOS_EMITIR'
const CONST_INCONCILIATIONVIEW = 'ROLE_FIN_FATURAMENTO_PAG_CONCILIACAO_VISUALIZAR'
const CONST_INREMITTANCEEMIT = 'ROLE_FIN_FATURAMENTO_PAG_REMESSA_EMITIR'
const CONST_INCNABINCL = 'ROLE_FIN_FATURAMENTO_PAG_RETORNO_INCLUIR'
const CONST_INCOVENANTFILEVIEW =  'ROLE_FIN_FISCAL_CONVENIO_115_VISUALIZAR'
const CONST_INACCOUNTINGFILESVIEW = 'ROLE_FIN_CONTABILIDADE_ARQUIVOS_VISUALIZAR'
const CONST_DBTEMPLATEINCLUDE = 'ROLE_FIN_FATURAMENTO_ND_TEMPLATE_INCLUIR'
const CONST_DBTEMPLATEUPDATE = 'ROLE_FIN_FATURAMENTO_ND_TEMPLATE_EDITAR'
const CONST_DBTEMPLATEVIEW = 'ROLE_FIN_FATURAMENTO_ND_TEMPLATE_VISUALIZAR'

const CONST_DBISSUEVIEW = 'ROLE_FIN_FATURAMENTO_ND_EMISSAO_NOTAS_VISUALIZAR'
const CONST_DBISSUEEMIT = 'ROLE_FIN_FATURAMENTO_ND_EMISSAO_NOTAS_EMITIR'
const CONST_DBISSUECANCEL = 'ROLE_FIN_FATURAMENTO_ND_EMISSAO_NOTAS_CANCELAR'
const CONST_DBISSUEDOWNLOAD = 'ROLE_FIN_FATURAMENTO_ND_EMISSAO_NOTAS_DOWNLOAD'
const CONST_DBISSUESEND = 'ROLE_FIN_FATURAMENTO_ND_EMISSAO_NOTAS_ENVIAR'
const CONST_DBISSUEDUPLICATEBILLET = 'ROLE_FIN_FATURAMENTO_ND_SEGUNDA_VIA_BOLETO_EMITIR'
const CONST_EXPORTREPORT = 'ROLE_FIN_EXPORTACAO_RELATORIOS_VISUALIZAR'
const CONST_TICKETS_DISCOUNT = 'ROLE_NOC_SAC_TICKETS_DESCONTO_VISUALIZAR'
const CONST_TICKETS_DISCOUNT_DOWNLOAD = 'ROLE_NOC_SAC_TICKETS_DESCONTO_DOWNLOAD'
const CONST_TICKETS_DISCOUNT_EXECUTAR = 'ROLE_NOC_SAC_TICKETS_DESCONTO_EXECUTAR'
const CONST_TICKETS_DISCOUNT_EDITAR = 'ROLE_NOC_SAC_TICKETS_DESCONTO_EDITAR'
const CONST_TICKETS_DISCOUNT_CALC = 'ROLE_NOC_SAC_TICKETS_DESCONTO_CALCULO_VISUALIZAR'
const CONST_TICKETS_DISCOUNT_DOWNLOAD_CALC = 'ROLE_NOC_SAC_TICKETS_DESCONTO_CALCULO_DOWNLOAD'
const CONST_TICKETS_DISCOUNT_EXECUTAR_CALC = 'ROLE_NOC_SAC_TICKETS_DESCONTO_CALCULO_EXECUTAR'
const CONST_TICKETS_DISCOUNT_EDITAR_CALC = 'ROLE_NOC_SAC_TICKETS_DESCONTO_CALCULO_EDITAR'
const CONST_NOTEBILLETIMPORTINCLUDE = 'ROLE_FIN_IMPORTACAO_NOTAS_BOLETOS_INCLUIR'
const CONST_ADM = 'ROLE_ADM_VISUALIZAR'
const CONST_ADM_EDITAR = 'ROLE_ADM_EDITAR'

const CONST_FININTEGRACAO = 'ROLE_FIN_INTEGRACAO_VISUALIZAR'

const CONST_INVOICECALCVIEW = 'ROLE_FIN_FATURAMENTO_MC_VISUALIZAR';
const CONST_INVOICECALCEMIT = 'ROLE_FIN_FATURAMENTO_MC_EMITIR';
const CONST_INVOICECALCCANCEL = 'ROLE_FIN_FATURAMENTO_MC_CANCELAR';
const CONST_INVOICECALCDOWNLOAD = 'ROLE_FIN_FATURAMENTO_MC_DOWNLOAD';
const CONST_INVOICECALCSEND = 'ROLE_FIN_FATURAMENTO_MC_ENVIAR';
const CONST_INVOICECALCEDIT = 'ROLE_FIN_FATURAMENTO_MC_EDITAR';
const CONST_INVOICECALCINSERT = 'ROLE_FIN_FATURAMENTO_MC_INCLUIR';
const CONST_INVOICECALCDELETE = 'ROLE_FIN_FATURAMENTO_MC_EXCLUIR';
const CONST_REOPENMEMORY = 'ROLE_FIN_REABRIR_MEMORIA_CALCULO_EXECUTAR';

export const userRoles = {

    inInvoiceView : CONST_ININVOICEVIEW,
    inInvoiceEmit : CONST_ININVOICEEMIT,
    inInvoiceCancel : CONST_ININVOICECANCEL,
    inInvoiceDownload : CONST_ININVOICEDOWNLOAD,
    inInvoiceSend : CONST_ININVOICESEND,
    inImportFileInclude : CONST_INIMPORTFILEINCLUDE,
    inDuplicateBilletEmit : CONST_INDUPLICATEBILLETEMIT,
    dunningView : CONST_DUNNINGVIEW,
    dunningInclude : CONST_DUNNINGINCLUDE,
    dunningEdit : CONST_DUNNINGEDIT,
    overduePanelView : CONST_OVERDUEPANELVIEW,
    overduePanelInclude : CONST_OVERDUEPANELINCLUDE,
    inIssuanceCalendarView : CONST_INISSUANCECALENDARVIEW,
    inBillingHistoryView : CONST_INBILLINGHISTORYVIEW,
    inInvoicingReportView : CONST_ININVOICINGREPORTVIEW,
    inClientBalanceView : CONST_INCLIENTBALANCEVIEW,
    inClientBalanceEmit : CONST_INCLIENTBALANCEEMIT,
    inConciliationView : CONST_INCONCILIATIONVIEW,
    inRemittanceEmit : CONST_INREMITTANCEEMIT,
    inCnabIncl : CONST_INCNABINCL,
    inCovenantFileView : CONST_INCOVENANTFILEVIEW,
    inAccountingFilesView : CONST_INACCOUNTINGFILESVIEW,
    dbTemplateInclude : CONST_DBTEMPLATEINCLUDE,
    dbTemplateUpdate : CONST_DBTEMPLATEUPDATE,
    dbTemplateView : CONST_DBTEMPLATEVIEW,
    dbIssueView : CONST_DBISSUEVIEW,
    dbIssueEmit : CONST_DBISSUEEMIT,
    dbIssueCancel : CONST_DBISSUECANCEL,
    dbIssueDownload : CONST_DBISSUEDOWNLOAD,
    dbIssueSend : CONST_DBISSUESEND,
    dbIssueDuplicateBillet : CONST_DBISSUEDUPLICATEBILLET,
    exportReport : CONST_EXPORTREPORT,
    ticketsDiscount : CONST_TICKETS_DISCOUNT,
    ticketsDiscountDownload: CONST_TICKETS_DISCOUNT_DOWNLOAD,
    ticketsDiscountExecutar: CONST_TICKETS_DISCOUNT_EXECUTAR,
    ticketsDiscountEditar: CONST_TICKETS_DISCOUNT_EDITAR,
    ticketsDiscountCalc : CONST_TICKETS_DISCOUNT_CALC,
    ticketsDiscountDownloadCalc: CONST_TICKETS_DISCOUNT_DOWNLOAD_CALC,
    ticketsDiscountExecutarCalc: CONST_TICKETS_DISCOUNT_EXECUTAR_CALC,
    ticketsDiscountEditarCalc: CONST_TICKETS_DISCOUNT_EDITAR_CALC,
    administracao : CONST_ADM,
    administracaoEditar: CONST_ADM_EDITAR,


    noteBilletImportInclude : CONST_NOTEBILLETIMPORTINCLUDE,

    invoiceCalcView : CONST_INVOICECALCVIEW,
    invoiceCalcEmit : CONST_INVOICECALCEMIT,
    invoiceCalcCancel : CONST_INVOICECALCCANCEL,
    invoiceCalcDownload : CONST_INVOICECALCDOWNLOAD,
    invoiceCalcSend : CONST_INVOICECALCSEND,
    invoiceCalcEdit : CONST_INVOICECALCEDIT,
    invoiceCalcInsert : CONST_INVOICECALCINSERT,
    invoiceCalcDelete : CONST_INVOICECALCDELETE,
    reopenMemory : CONST_REOPENMEMORY,

    allReceiptsViewRoles : [CONST_RECEIPTS, CONST_INCLIENTBALANCEVIEW, CONST_INCONCILIATIONVIEW, CONST_INCNABINCL],
    allIntegracaoViewRoles : [CONST_FININTEGRACAO],
    allInvoiceViewRoles : [CONST_ININVOICEVIEW],
    allInvoiceCalcViewRoles : [CONST_INVOICECALCVIEW, CONST_INIMPORTFILEINCLUDE],
    allInvoiceActionRoles : [CONST_ININVOICEEMIT, CONST_ININVOICESEND, CONST_ININVOICEDOWNLOAD],
    allDunningViewRoles : [CONST_DUNNINGVIEW, CONST_OVERDUEPANELVIEW],
    allDebitNotesRoles : [CONST_DBTEMPLATEVIEW, CONST_DBISSUEVIEW],
    allDebitNotesActionRoles : [CONST_DBISSUEEMIT, CONST_DBISSUEDOWNLOAD, CONST_DBISSUESEND]

}
